### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by wapmorgan** [wapmorgan/PackageBuilder#1]
- [ ] Add `--simple` and `--advanced` options to builder
- [ ] Extend git version parser to understand tags
- [ ] Build a package from package name only (`pbuilde build composer/composer`)

**Comment by aazon** [comment]
I would propose to add a cli parameter with desired version of the package. We do `git archive` to fetch a source code and thus there is no `.git` folder there. 

The second possibility to specify a new version in `composer.json` does not look convenient as for me.
